# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-extraneous-dependencies: 
    - error
    - devDependencies: true
extends:
  - airbnb-base
env: 
    "jest": true
