extends:
  - airbnb-base
env: 
    "jest": true
    
rules:
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
  import/no-extraneous-dependencies: 
    - error
    - devDependencies: true
